#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if command -v systemctl >/dev/null 2>&1; then
        systemctl --global disable linux-soundboard-engine.service >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#
